stages:
    - fetch
    - despliegue
repository:
  stage: fetch
  script:
    - cd /var/www/miudl/
    - git fetch -all
deploy:
  stage: despliegue
  script:
    - cd /var/www/miudl/
    - npm run dev
    #- composer update

