stages:
    - fetch
    - despliegue
repository:
  stage: fetch
  script:
    - cd /var/www/miudl/
    - git fetch origin master
    - git reset --hard FETCH_HEAD
    - git clean -df
deploy:
  stage: despliegue
  script:
    - cd /var/www/miudl/
    - npm run dev
    #- composer update

